### ISSUE TITLE
如何使用控制器来处理消息

### ISSUE THREAD

**Issue by pf666nb** [Kloping/SimpleMiraiCore#1]
如题，我将项目拉下来，能成功运行，但是不知道如何让Control层来接收并处理消息，希望能够指点一下

**Comment by Kloping** [comment]
Action  里 写 预匹配 的 文本 
其方法就是 匹配后要执行的方法

**Comment by pf666nb** [comment]
您可能没太理解我表达的问题，就像您写的示例中，启动后，我向机器人发送对应的actions中的消息，并没有被响应，我想知道的是需要配置什么或者是该如何被响应，希望能够指导一下

**Comment by Kloping** [comment]
https://github.com/Kloping/SimpleMiraiCore/blob/master/src/main/core/io/github/kloping/Mcore/java/ListenerHosts/BaseMessageListener.java#L38

**Comment by Kloping** [comment]
由此 触发

**Comment by pf666nb** [comment]
![image](https://user-images.githubusercontent.com/56686784/149644244-b7868e69-300d-4749-8732-e346ecf57e8b.png)
![image](https://user-images.githubusercontent.com/56686784/149644255-a6cd963f-e2dd-4884-bdd4-5faa795bc8b3.png)
![image](https://user-images.githubusercontent.com/56686784/149644261-ff5addb0-385f-45af-9195-4ad78cd3cba0.png)
我这样设置后，好像也依然无法触发，是因为这个No match for 有关吗？

**Comment by Kloping** [comment]
待会重新拉取一下代码,看看问题能不能解决

**Comment by pf666nb** [comment]
好的麻烦了！

**Comment by pf666nb** [comment]
很遗憾的是，并没有被解决，无论是群聊消息还是单独聊天都是”No match for 你好啊“，不知道您本地是否可以正常的运行，启动时候有个Error不知道是否与这个错误有关
![image](https://user-images.githubusercontent.com/56686784/149645892-981a1024-8c6d-4e62-83c1-2febd6b7b9f3.png)

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/149645951-a31b0c8b-c903-4d4a-be36-98fd796e3ef3.png)
![image](https://user-images.githubusercontent.com/87743020/149645953-4a183ab9-44d0-4e16-b386-fed10323431c.png)

**Comment by pf666nb** [comment]
十分感谢您的帮助，我已经能成功运行并且相应，出现这个问题的原因是因为上面提到的报错，我点您写的Tool类进行断点调试
![image](https://user-images.githubusercontent.com/56686784/149646057-c1134cca-cc4d-42b7-b793-7d6658d1f13c.png)
发现出现了路径乱码，我才发现我的项目clone到桌面上面的，所以路径中包含了中文，导致类无法被扫描，我放到全英文路径这个问题就消失了，有考虑对中文路径的支持吗，如果没有就close了，再次十分感谢

**Comment by Kloping** [comment]
> 十分感谢您的帮助，我已经能成功运行并且相应，出现这个问题的原因是因为上面提到的报错，我点您写的Tool类进行断点调试 ![image](https://user-images.githubusercontent.com/56686784/149646057-c1134cca-cc4d-42b7-b793-7d6658d1f13c.png) 发现出现了路径乱码，我才发现我的项目clone到桌面上面的，所以路径中包含了中文，导致类无法被扫描，我放到全英文路径这个问题就消失了，有考虑对中文路径的支持吗，如果没有就close了，再次十分感谢

好的客气
